services:
  - type: web
    name: multiple-disease-predictor
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        value: mysql://root:ePDnfvrvQXybHChAQMAXAmUvAKhRzMKj@switchback.proxy.rlwy.net:58858/railway
